replicaCount: 1

image:
  repository: nginxdemos/hello
  tag: "0.3"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: traefik
  host: ""
  clusterIssuer: letsencrypt-prod
  tlsSecretName: frontend-uat-tls

configmap:
  data:
    APP_ENV: uat
    APP_NAME: frontend

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  cpuUtilization: 70
