replicaCount: 1

image:
  repository: nginxdemos/hello
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: traefik
  host: myaks.nt-nick.link
  clusterIssuer: letsencrypt-prod
  tlsSecretName: web-app-tls

configmap:
  data:
    APP_ENV: production

hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 70
