apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-uat
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ntnick-22/gitops.git
    targetRevision: main
    path: helm-charts/backend
    helm:
      valueFiles:
        - values-uat.yaml
  destination:
    name: in-cluster
    namespace: uat
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
